name: .NET Framework Upgrade

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]


permissions:
  contents: write  # required for GITHUB_TOKEN to push

jobs:
  update:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # ensure branch history
      - name: Make changes
        env:
          AMP_API_KEY: ${{ secrets.AMP_API_KEY }}
        run: npx @sourcegraph/amp@latest --dangerously-allow-all -x "Migrate this from dotnet 4.8 to net8.0 using the dotnet upgrade assistant. Install it using dotnet tool install -g upgrade-assistant and then run upgrade-assistant upgrade --entry-point <path-to-sln-or-csproj> --non-interactive for all applicable sln and csproj files. Reference online documentation for more info on how to use the upgrade assistant."
      - name: Create pull request
        id: create_pr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Apply automated .NET upgrade assistant changes"
          branch: "amp/upgrade-assistant"
          branch-suffix: timestamp
          title: "Automated: .NET upgrade assistant changes"
          body: |
            This PR was created automatically by the migration workflow.
            It contains changes produced by running Amp with the .NET Upgrade Assistant.
          labels: automated, amp
          delete-branch: true

